# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Blogue
tagline:          'Franco Peschiera'
description:      'Radically unpopular rants from a random guy with no (secret) agenda'
url:              https://pchtsp.github.io/
baseurl:          /

author:
  name:           'Franco Peschiera'
  url:            https://github.com/pchtsp

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/pchtsp/blogue

plugins:
  - jekyll-gist
  - jekyll-paginate